# -*- coding: utf-8 -*-
"""CKD_Machine_Learning_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ogywx6EtA4d2-f5hstUYyilj4iy-_8Pu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('chronic dieases.zip')

df.head()

print("Rows and Columns:")
print(df.shape)

df.info()

# Missing values

missing_values = df.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

print("Total Missing Values:", df.isnull().sum().sum())

df.describe()

print("Duplicate Rows:", df.duplicated().sum())

df = df.drop("id", axis=1)

df.head()

df.replace(r'^\s*\?$', np.nan, regex=True, inplace=True)

print(df.isnull().sum().sum())

numeric_columns = [
    'age','bp','sg','al','su','bgr',
    'bu','sc','sod','pot','hemo'
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Numerical columns
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

# Categorical columns
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print("Remaining Missing Values:")
print(df.isnull().sum().sum())

plt.figure(figsize=(6,4))
sns.countplot(x='classification', data=df)

plt.title('CKD Classification Distribution')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['age'], bins=20, kde=True)

plt.title('Age Distribution')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['bp'], bins=20, kde=True)

plt.title('Blood Pressure Distribution')
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x='classification',
            y='hemo',
            data=df)

plt.title('Hemoglobin by CKD Status')
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x='classification',
            y='sc',
            data=df)

plt.title('Serum Creatinine by CKD Status')
plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_encoded = df.copy()

for col in df_encoded.columns:
    if df_encoded[col].dtype == 'object':
        df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))

plt.figure(figsize=(14,10))

sns.heatmap(
    df_encoded.corr(),
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

df.describe()

df['classification'].unique()

df['classification'] = df['classification'].str.strip()

df['classification'].unique()

# Create anemia feature

df['Anemia_Status'] = np.where(df['hemo'] < 12,
                               'Anemic',
                               'Normal')

df[['hemo','Anemia_Status']].head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col].astype(str))

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

X = df.drop('classification', axis=1)
y = df['classification']

selector = SelectKBest(score_func=chi2, k=10)

X_selected = selector.fit_transform(X, y)

selected_features = X.columns[selector.get_support()]

print(selected_features)

X = df.drop('classification', axis=1)
y = df['classification']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

print("Accuracy:",
      accuracy_score(y_test, y_pred_lr))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42
)

rf.fit(X_train_scaled, y_train)

y_pred_rf = rf.predict(X_test_scaled)

print("Accuracy:",
      accuracy_score(y_test, y_pred_rf))

from sklearn.svm import SVC

svm = SVC()

svm.fit(X_train_scaled, y_train)

y_pred_svm = svm.predict(X_test_scaled)

print("Accuracy:",
      accuracy_score(y_test, y_pred_svm))

from sklearn.metrics import classification_report

print("Logistic Regression")
print(classification_report(y_test, y_pred_lr))

print("Random Forest")
print(classification_report(y_test, y_pred_rf))

print("SVM")
print(classification_report(y_test, y_pred_svm))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_svm)

plt.figure(figsize=(5,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("SVM Confusion Matrix")

plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators':[50,100,200],
    'max_depth':[None,5,10],
    'min_samples_split':[2,5]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy'
)

grid.fit(X_train_scaled, y_train)

print("Best Parameters:")
print(grid.best_params_)

print("Best Score:")
print(grid.best_score_)

best_rf = grid.best_estimator_

importance = best_rf.feature_importances_

importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

print(importance_df.head(10))

import joblib

joblib.dump(svm, "ckd_model.pkl")
joblib.dump(scaler, "scaler.pkl")

from google.colab import files

files.download("ckd_model.pkl")
files.download("scaler.pkl")

from sklearn.metrics import roc_curve, roc_auc_score

svm_prob = SVC(probability=True)
svm_prob.fit(X_train_scaled, y_train)

y_prob = svm_prob.predict_proba(X_test_scaled)[:,1]

auc = roc_auc_score(y_test, y_prob)

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(6,4))

plt.plot(fpr, tpr, label=f'AUC = {auc:.3f}')
plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - SVM")
plt.legend()

plt.show()

print("AUC:", auc)

from sklearn.model_selection import learning_curve

train_sizes, train_scores, test_scores = learning_curve(
    svm,
    X_train_scaled,
    y_train,
    cv=5,
    scoring='accuracy'
)

train_mean = train_scores.mean(axis=1)
test_mean = test_scores.mean(axis=1)

plt.figure(figsize=(7,5))

plt.plot(train_sizes,
         train_mean,
         label='Training Accuracy')

plt.plot(train_sizes,
         test_mean,
         label='Validation Accuracy')

plt.xlabel("Training Size")
plt.ylabel("Accuracy")
plt.title("Learning Curve")
plt.legend()

plt.show()

"""Conclusion
This study developed machine learning models to predict chronic kidney disease using clinical and laboratory measurements. Data cleaning was performed to handle missing values and prepare the dataset for analysis. Exploratory data analysis revealed meaningful relationships between several clinical features and CKD status. Feature selection identified the most informative predictors, including hemoglobin, serum creatinine, blood urea, and hypertension. Logistic Regression, Random Forest, and Support Vector Machine models were evaluated. Among all models, SVM achieved the highest performance with an accuracy of 98.75%, demonstrating excellent capability in distinguishing CKD and non-CKD patients. These findings indicate that machine learning can serve as an effective tool for supporting early CKD detection.

Limitation
The dataset contained only 400 patient records, which may limit generalization to larger populations. In addition, the study relied on a single dataset and did not include external validation. Some clinical variables originally contained missing values that required imputation, which may introduce uncertainty into the final model.

Future work
Future studies may incorporate larger and more diverse datasets to improve model robustness. Additional machine learning and deep learning algorithms could be explored and compared. External validation using independent patient cohorts and deployment within clinical decision-support systems may further enhance the practical applicability of the developed model.
"""

print(df.columns.tolist())

import joblib

joblib.dump(svm_prob, "ckd_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "features.pkl")

from google.colab import files

files.download("ckd_model.pkl")
files.download("scaler.pkl")
files.download("features.pkl")

app_code = """
import streamlit as st
import pandas as pd
import joblib

model = joblib.load("ckd_model.pkl")
scaler = joblib.load("scaler.pkl")
features = joblib.load("features.pkl")

st.title("Chronic Kidney Disease Prediction App")
st.write("Enter patient clinical values to predict CKD status.")

input_data = {}

for feature in features:
    input_data[feature] = st.number_input(f"Enter {feature}", value=0.0)

input_df = pd.DataFrame([input_data])
input_scaled = scaler.transform(input_df)

prediction = model.predict(input_scaled)[0]

st.subheader("Prediction Result")

if prediction == 1:
    st.error("The patient is predicted to have Chronic Kidney Disease.")
else:
    st.success("The patient is predicted to NOT have Chronic Kidney Disease.")
"""

with open("app.py", "w") as f:
    f.write(app_code)